/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package sistema;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.Statement;
import java.sql.PreparedStatement;
import java.sql.ResultSet;

/**
 *
 * @author Jesus Emmanuel Lopez
 */
public class EliminarUsuarios extends javax.swing.JInternalFrame {
    private int idUsuario;
    /**
     * Creates new form EliminarUsuarios
     */
    public EliminarUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblEUsurio = new javax.swing.JLabel();
        lblETipo = new javax.swing.JLabel();
        txtEUsuario = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();
        lblENombre = new javax.swing.JLabel();
        txtENombre = new javax.swing.JTextField();
        btnEBuscar = new javax.swing.JButton();
        txtEliRol = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Eliminar Usuarios");

        lblEUsurio.setText("Usuario :");

        lblETipo.setText("Tipo :");

        txtEUsuario.setEnabled(false);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        lblENombre.setText("Nombre :");

        txtENombre.setEnabled(false);

        btnEBuscar.setLabel("Buscar");
        btnEBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEBuscarActionPerformed(evt);
            }
        });

        txtEliRol.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(222, 222, 222))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(btnEliminar)
                        .addGap(118, 118, 118)
                        .addComponent(btnCerrar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblENombre)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtENombre)
                                .addGap(18, 18, 18)
                                .addComponent(btnEBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblETipo)
                                    .addComponent(lblEUsurio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtEUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtEliRol, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEUsurio)
                    .addComponent(txtEUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblENombre)
                    .addComponent(txtENombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblETipo)
                    .addComponent(txtEliRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnCerrar))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(81, 81, 81))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String user = "root";
        String url = "jdbc:mysql://localhost:3306/";
        String password = "root";
        String bd = "requerimientos";
        String conector = "com.mysql.cj.jdbc.Driver";
        try{    
            Class.forName(conector);
            Connection conexion = DriverManager.getConnection(url+bd,user,password);
            
            String sql = "DELETE FROM usuarios WHERE id = " + this.idUsuario + ";";
            PreparedStatement consulta = conexion.prepareStatement(sql);
            consulta.executeUpdate();
            JOptionPane.showMessageDialog(null, "El usuario : " + this.txtEUsuario.getText() + " se elimino con exito");
            conexion.close();
            this.txtENombre.setText("");
            this.txtEUsuario.setText("");
            this.txtEliRol.setText("");
        }catch(ClassNotFoundException | SQLException message){
            JOptionPane.showMessageDialog(null, "Error al tratar de eliminar al usuario : " + this.txtEUsuario);
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, message);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEBuscarActionPerformed
        String nombreUsuario = JOptionPane.showInputDialog("Ingresa el nombre del usuario");
        try{
            String user = "root";
            String url = "jdbc:mysql://localhost:3306/";
            String password = "root";
            String bd = "requerimientos";
            String conector = "com.mysql.cj.jdbc.Driver";
            Class.forName(conector);
            Connection conexion = DriverManager.getConnection(url+bd,user,password);

            String query = "SELECT u.id, t.nombre as rol, u.usuario, u.nombre FROM usuarios AS u "
                            + "INNER JOIN tipo_usuarios AS t ON u.id_tipo_usuarios = t.id"
                            + " WHERE u.nombre = '"+ nombreUsuario +"';";
             //WHERE nombre = '" + nombreUsuario + "';"
            Statement consulta = conexion.createStatement();
            ResultSet respuesta = consulta.executeQuery(query);
            while(respuesta.next()){
              this.txtENombre.setText(respuesta.getString(4));
              this.txtEUsuario.setText(respuesta.getString(3));
              this.txtEliRol.setText(respuesta.getString(2));
              this.idUsuario = respuesta.getInt(1);
            }
            conexion.close();
        }catch(ClassNotFoundException | SQLException message){
            JOptionPane.showMessageDialog(null,"El usuario: " + nombreUsuario + " no se encuentra en la Base de Datos");
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, message);
        }
    }//GEN-LAST:event_btnEBuscarActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
       this.hide();
    }//GEN-LAST:event_btnCerrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblENombre;
    private javax.swing.JLabel lblETipo;
    private javax.swing.JLabel lblEUsurio;
    private javax.swing.JTextField txtENombre;
    private javax.swing.JTextField txtEUsuario;
    private javax.swing.JTextField txtEliRol;
    // End of variables declaration//GEN-END:variables
}
